Overhaul & simplify lssh
We now rely on .bashrc within a containers to set the terminal window's
title. Now we only call termname *after* the ssh, to retore our host's
default terminal title.

Because 'termname' is now a function defined in .bashrc, I had to tweak
our shebang line to make this script run as an interactive session. I
suspect I shouldn't have to do this - shouldn't subshells of my initial
interactive login inherit the functions defined in .bashrc? But for some
reason they do not, hence, this hack in line 1.

Simplify the logic for automatically cd-ing to a directory within the
container. Now we try the following in order, to see which succeeds:

* The host's `pwd`, if it exists in the container.
* The directory `~/src/<alias>`, using the alias our caller used to
  specify the container to run.
* If neither of these exit, we will default to the container $HOME.

Add a bunch of comments to explain what this script does, how, and why.

diff --git a/bin/lssh b/bin/lssh
index 63ee351..7575837 100755
--- a/bin/lssh
+++ b/bin/lssh
@@ -1,36 +1,40 @@
-#!/usr/bin/env bash
+#!/usr/bin/env -S bash -i
+# The above flags let this script use functions (eg termname) from the .bashrc

-set -e # exit on error
-# set -x # debugging output
-set -u # exist on unset variables
+# ssh to given container or project alias.
+# Usage:
+#
+#   lssh <project-alias>
+#
+# Requires containers to have an IPv4 address, and name resolution to be working.
+# Use 'lalias' to list the available containers and their aliases.
+
+set -eu # -x

 if [ "$#" -ne 1 ] ; then
-    echo "Usage: lssh <projectname>"
-    return
+    echo "Usage: lssh <project-alias>"
+    echo "See available project aliases using 'lalias' command."
+    exit 1
 fi
+
 alias="$1"
 container=$(lalias $alias)
-host="$container.lxd"
-
-destdir="$HOME"
-if [ -d "$HOME/src/$alias" ]; then
-    destdir="$HOME/src/$alias"
-fi
-
-tname="$container"
-if [ "$alias" != "$container" ]; then
-    tname="$alias on $container"
-fi
-
-termname "$tname"
-
-# ssh to container.
-# Requires containers to have IPv4 address,
-# and name resolution to be working.
-# -A: Forward ssh-agent. So we can, for example,
-#     hit github using passphrases cached by ssh-agent.
-# -t: Force pseudo-terminal allocation. (I forget why.)
-ssh -A -t "${host}" -- "cd $destdir; exec -l $SHELL"

-termname "Terminal"
+# We call ssh with:
+#
+#   -A: Forward ssh-agent. So we can, for example, hit github using passphrases
+#       cached by ssh-agent.
+#   -t: Force pseudo-terminal allocation. (I forget why.)
+#
+# cd to the same dir as we're currently in on the host, if it exists. Fallback
+# to a dir named for the project alias (eg if connecting to container 'ident',
+# cd $HOME/src/ident, which ought to exist. If that fails, we'll be in $HOME.
+# Exec a new shell to let us type commands from the resulting dir.
+ssh -A -t "${container}.lxd" -- \
+    "cd $(pwd) 2>/dev/null || \
+     cd "$HOME/src/$alias" 2>/dev/null ; \
+     exec -l $SHELL"
+
+# Restore the our host's regular title for the terminal window.
+termname

diff --git a/bin/lssh b/bin/lssh
--- a/bin/lssh
+++ b/bin/lssh
@@ -1,36 +1,40 @@
-#!/usr/bin/env bash
+#!/usr/bin/env -S bash -i
+# The above flags let this script use functions (eg termname) from the .bashrc
 
-set -e # exit on error
-# set -x # debugging output
-set -u # exist on unset variables
+# ssh to given container or project alias.
+# Usage:
+#
+#   lssh <project-alias>
+#
+# Requires containers to have an IPv4 address, and name resolution to be working.
+# Use 'lalias' to list the available containers and their aliases.
+
+set -eu # -x
 
 if [ "$#" -ne 1 ] ; then
-    echo "Usage: lssh <projectname>"
-    return
+    echo "Usage: lssh <project-alias>"
+    echo "See available project aliases using 'lalias' command."
+    exit 1
 fi
+
 alias="$1"
 container=$(lalias $alias)
-host="$container.lxd"
 
-destdir="$HOME"
-if [ -d "$HOME/src/$alias" ]; then
-    destdir="$HOME/src/$alias"
-fi
+# We call ssh with:
+#
+#   -A: Forward ssh-agent. So we can, for example, hit github using passphrases
+#       cached by ssh-agent.
+#   -t: Force pseudo-terminal allocation. (I forget why.)
+#
+# cd to the same dir as we're currently in on the host, if it exists. Fallback
+# to a dir named for the project alias (eg if connecting to container 'ident',
+# cd $HOME/src/ident, which ought to exist. If that fails, we'll be in $HOME.
+# Exec a new shell to let us type commands from the resulting dir.
+ssh -A -t "${container}.lxd" -- \
+    "cd $(pwd) 2>/dev/null || \
+     cd "$HOME/src/$alias" 2>/dev/null ; \
+     exec -l $SHELL"
 
-tname="$container"
-if [ "$alias" != "$container" ]; then
-    tname="$alias on $container"
-fi
-
-termname "$tname"
-
-# ssh to container.
-# Requires containers to have IPv4 address,
-# and name resolution to be working.
-# -A: Forward ssh-agent. So we can, for example,
-#     hit github using passphrases cached by ssh-agent.
-# -t: Force pseudo-terminal allocation. (I forget why.)
-ssh -A -t "${host}" -- "cd $destdir; exec -l $SHELL"
-
-termname "Terminal"
+# Restore the our host's regular title for the terminal window.
+termname
 
