Convert big if...else into a small early return

diff --git a/bin/lxc-setup b/bin/lxc-setup
--- a/bin/lxc-setup
+++ b/bin/lxc-setup
@@ -79,35 +79,35 @@ function process_container {
     local container="$1"
     echo -n "$container: " >&2
     # If this is a valid container
-    if grep -q "^$container$" <<<"$(lxcls)" ; then
-
-        # If the container isn't running, start it.
-        is_initially_running=$(is_running $container)
-        if [ "$is_initially_running" = false ] ; then
-            echo -n "starting.." >&2
-            lxc start "$container"
-            # Wait for the container to start responding to ssh.
-            # Without this, the subsequent scp would sometimes fail with 'lost connection'.
-            lxc-wait "$container"
-            echo -n " " >&2
-        fi
-
-        # Actually copy the files, the point of this whole thing!
-        echo -n "copying... "
-        configure_container "$container"
-
-        # If we started the container, now we stop it again,
-        # to leave things how we found them.
-        if [ "$is_initially_running" = false ] ; then
-            echo -n "stopping... " >&2
-            lxc stop "$container" &
-        fi
-
-        echo "ok" >&2
-    else
+    if ! grep -q "^$container$" <<<"$(lxcls)" ; then
         echo "Not a container" >&2
         exitval=1
+        return
     fi
+
+    # If the container isn't running, start it.
+    is_initially_running=$(is_running $container)
+    if [ "$is_initially_running" = false ] ; then
+        echo -n "starting.." >&2
+        lxc start "$container"
+        # Wait for the container to start responding to ssh.
+        # Without this, the subsequent scp would sometimes fail with 'lost connection'.
+        lxc-wait "$container"
+        echo -n " " >&2
+    fi
+
+    # Actually copy the files, the point of this whole thing!
+    echo -n "copying... "
+    configure_container "$container"
+
+    # If we started the container, now we stop it again,
+    # to leave things how we found them.
+    if [ "$is_initially_running" = false ] ; then
+        echo -n "stopping... " >&2
+        lxc stop "$container" &
+    fi
+
+    echo "ok" >&2
 }
 
 exitval=0
