Modernize nvim wrapper script 'ni'
Previously this unconditionally opened a new terminal to run nvim in.
This is disruptive: To use EDITOR=ni, special care has to be taken to
run the terminal app synchronously, and it prevents the same EDITOR
setting being shared in containers (since they can't open new terminal
GUI applications on the host desktop.)

So this new approach is simpler:
* Only open a new terminal if we are not already running in one
* Otherwise, use the one we're in
* If 'nvim' is not on the PATH, fallback to 'vim'

This allows us to share the EDITOR setting on the host and on containers
(simplifying .profile), remove the 'nis' alternate alias for 'ni', and
has bonuses such as allowing me to bind a desktop custom key shortcut to
'ni', and it just does the right thing (open a new terminal to run nvim
in it).

Also delete related wrapper 'niv', which I have not used in years.
Suspect it existed to quash noisy messages from the terminal or from
nvim, but I don't see any today, so perhaps this is no longer a problem.

Also: Install nvim in our lxc containers.

diff --git a/bin/ni b/bin/ni
--- a/bin/ni
+++ b/bin/ni
@@ -1,17 +1,25 @@
 #!/usr/bin/env bash
 
-# Open a new terminal in solarized profile, and run neovim in it.
+# Wrapper for nvim.
 #
-# If invoked as 'nis' (ni synchronous), will block until neovim exits.
-# Intended for use as $EDITOR.
+# Launch a terminal to run nvim in, unless we are already in one. This means we
+# can be called from the command-line and from situations with no terminal
+# (e.g. a desktop custom shortcut key)
 #
-if [ "$(basename $0)" == "nis" ]; then
-    wait="--wait"
-else
-    wait=""
+# Fallback to vim if nvim is not installed, to make it safe to use this for things
+# one would rather not fail, such as $EDITOR.
+
+# Prefer nvim, fallback to vim
+editor=nvim
+if ! type -P nvim >/dev/null; then
+    editor=vim
 fi
 
-if ! gnome-terminal --profile editor $wait &>/dev/null -- nvim "$@" ; then
-    vim "$@"
+# If we are not in a terminal, open one
+# Run the terminal synchronously (--wait) so that we work as $EDITOR
+if [ "$(tty)" = "not a tty" ]; then
+    gnome-terminal --wait -- $editor "$@"
+else
+    $editor "$@"
 fi
 
